CREATE TABLE "SCOTT"."T_MEMBER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PWD" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"JOINDATE" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("ID");